apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose --file docker-compose.yaml convert
    kompose.version: 1.26.1 (a9d05d509)
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-1:658861819646:certificate/ab80fca5-f242-48fe-b7b2-f07984d87229
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  creationTimestamp: null
  labels:
    io.kompose.service: teedy-server-ssl
  name: teedy-server-ssl
spec:
  ports:
    - name: "ssl"
      port: 443
      targetPort: 8080
  selector:
    io.kompose.service: teedy-server
  type: LoadBalancer
status:
  loadBalancer: {}
